### ISSUE TITLE
version mismatch

### ISSUE THREAD

**Issue by csrgxtu** [arcticicestudio/nord-gnome-terminal#21]
[WARN] Detected incompatible GNOME Terminal version 3.6.2 (< 3.8)
[ERR] The installed GNOME Terminal version '3.6.2' is not compatible with the required (dconf migrated) version >= 3.8!

**Comment by arcticicestudio** [comment]
This is a warning/error thrown by the script. GNOME Terminal versions < 3.8 are based on the [GConf][w] backend [which is deprecated since GNOME 3][mig]:

> [...] It was deprecated as part of the GNOME 3 transition. Migration to its replacement, GSettings and dconf, is ongoing.

GNOME Terminal version < 3.6 is also very outdated and not shipped with any distribution and package lists anymore. That's why this theme only supports GNOME Terminal versions > 3.8 which are running dconf with GSettings as backend.

You should consider to update to a later GNOME Terminal version. This is also important to get fixes for bugs and maybe security issues!

[w]: https://en.wikipedia.org/wiki/GConf
[mig]: https://wiki.gnome.org/Initiatives/GnomeGoals/GSettingsMigration
