### ISSUE TITLE
Is there a simple way to uninstall the profile?

### ISSUE THREAD

**Issue by welblaud** [arcticicestudio/nord-gnome-terminal#25]
It is not possible to select and remove the profile via the profile menu. I would like to use the gogh script for installing nord instead but can't figure out how to remove the profile at first.

**Comment by arcticicestudio** [comment]
Hi @welblaud 👋 
The install script clones the default profile of GNOME terminal that is created when the app gets installed. To uninstall Nord, normally the profile can simply be removed so only the _Default_ profile should remain. Using he latest version of GNOME terminal, you can delete the profile by opening the settings, go to the “Profiles“ section, select the “Nord“ profile and click on the <kbd>-</kbd> button to remove it.
Can you please post a screenshot of your settings, I can't reproduce your problem since I'm able to delete the profile using the described method.

**Comment by welblaud** [comment]
Got it, thanks! :+1:
