### ISSUE TITLE
Can't enable light background

### ISSUE THREAD

**Issue by ghost** [arcticicestudio/nord-gnome-terminal#28]
I have installed this theme but by default it's uses dark background. Now how i can use light background?

**Comment by arcticicestudio** [comment]
Hi @Donboscow :wave: 
This is by design since Nord GNOME Terminal is a _dark_ based theme so there is currently no light background color available. There are plans to support some kind of „daylight”/„bright” theme mode variant, but at the moment you need to customize on your own. To do so you can go to your [_GNOME Terminal_ profile][p] preferences, switch to the „Colors” tab and [customize the background color][cct], e.g. by using [nord4][] from the [Snow Storm][ss] color palette instead of [nord0][] from the [Polar Night][pn] palette.

[p]: https://help.gnome.org/users/gnome-terminal/stable/pref-profiles.html.en
[cct]: https://help.gnome.org/users/gnome-terminal/stable/app-colors.html.en#custom-scheme
[ss]: https://www.nordtheme.com/docs/colors-and-palettes#snow-storm
[pn]: https://www.nordtheme.com/docs/colors-and-palettes#polar-night
[nord4]: https://www.nordtheme.com/docs/colors-and-palettes#nord4
[nord0]: https://www.nordtheme.com/docs/colors-and-palettes#nord0

**Comment by cachandlerdev** [comment]
> There are plans to support some kind of „daylight”/„bright” theme mode variant, but at the moment you need to customize on your own.

Has there been any update on this since 2019? I was hoping to sync a dark and light version of the theme with the rest of my desktop.
