### ISSUE TITLE
Installed Nord - Can't find Profile (Works for 20.04.4 LTS, bug with 20.04 LTS)

### ISSUE THREAD

**Issue by Wilann** [arcticicestudio/nord-gnome-terminal#35]
I've installed Nord, but can't find where to activate it. 
On Ubuntu 20.04, there doesn't seem to be a "Profiles" tab. 

![Screenshot from 2021-02-24 15-43-00](https://user-images.githubusercontent.com/40744757/109063607-5ad60400-76b7-11eb-8d80-2045ee6ebb3b.png)
![Screenshot from 2021-02-24 15-44-14](https://user-images.githubusercontent.com/40744757/109063614-5d385e00-76b7-11eb-8ca0-475f31d84e12.png)

I saw this in the requirements, but have no idea how to add dconf and uuidgen to my PATH. (A search didn't yield any results either) 
`The installation script requires dconf and uuidgen (util-linux) to be available on your PATH to create a new profile and generate a random profile UUID.`

**Comment by arcticicestudio** [comment]
Hi @Wilann :wave:

Looks like this is related to #19 and #20.

The problem is that the underlying library, that is used to set the [`GSetting` values][gsettings] (it's a kind of store for GNOME application configurations), by default uses the `memory` backend so settings will not be saved or shared with other applications. This means that the script works fine, but the changes made with `dconf` are read-only and will be dropped as soon as the script finish.

Can you please try to reproduce the problem when running the following line before the install script:

```sh
export GIO_EXTRA_MODULES=/usr/lib/x86_64-linux-gnu/gio/modules
```

[gsettings]: https://developer.gnome.org/gio/stable/GSettings.html

**Comment by Wilann** [comment]
Wow it worked! Nord is now installed! I'm new to Linux so I'm not sure what all this means. 
Thank you so much!

**Comment by luke-pritch** [comment]
Ran into this myself just now and this fixed the same issue on my machine running Ubuntu 20.04 as well.

**Comment by Wilann** [comment]
Updated to Ubuntu 20.04.2 LTS from 20.04 LTS and re-installed from scratch. I didn't need to `export` line from above. Seemed to be fixed in this version.

**Comment by arcticicestudio** [comment]
@luke-pritch @Wilann Thanks for your feedback, I guess this problem can be pinned to Ubuntu but doesn't seem to affect other GNOME-based distributions. I'll have to check if it is possible to safely modify the environment variable only during the runtime of he installation script without risking to override its value when it was already set.
